spring:
  datasource:
    url: jdbc:mysql://EC2_IP_ADDRESS:3306/inClassPractice
    username: DB_USERNAME
    password: DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      indent_output:

server:
  address: 0.0.0.0
  port: 8080