name: spring-boot app. to dockerhub

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃 - 소스 코드 가져오기
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test  # 테스트를 제외하고 빌드 수행

      # GitHub Secrets에서 IP 주소를 가져와 application.yml 파일의 IP 설정 값 업데이트
      - name: Update IP in application.yml
        run: |
          sed -i "s/IP_ADDRESS_PLACEHOLDER/${{ secrets.EC2_IP_ADDRESS }}/g" src/main/resources/application.yml

      # DockerHub 로그인 (GitHub Secrets 사용)
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 DockerHub에 푸시
      - name: DockerHub Upload
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: springbootapp_inclass
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:$IMAGE_TAG
          docker push $NAME/$REPO:$IMAGE_TAG